version: '2'
services:
    web:
        build: ./server
        command: npm run start-dev
        volumes:
            - ./server:/describeIt/
            - /describeIt/node_modules
        ports:
            - "8000:8000"
        depends_on:
            - postgres
        environment:
            DATABASE_URL: postgres://describeItApp:describeIt@postgres/describeIt
    postgres:
        image: postgres:9.6-alpine
        environment:
          POSTGRES_USER: describeItApp
          POSTGRES_DB: describeIt
          POSTGRES_PASSWORD: describeIt
        volumes:
          - postgres_data:/var/lib/postgresql/data
        ports:
          - "127.0.0.1:6432:5432"
volumes:
  postgres_data:

