version: '2'
services:
    web:
        build: ./server
        command: npm run start-dev
        volumes:
            - ./server:/describeIt/
            - /describeIt/node_modules
        ports:
            - "8000:8000"
        depends_on:
            - postgres
        environment:
            DATABASE_URL: postgres://describeItApp@postgres/describeIt
    postgres:
        image: postgres:9.6.2-alpine
        environment:
            POSTGRES_USER: describeItApp
            POSTGRES_DB: describeIt
